# yaml-language-server: $schema=schema.default.json

run:
  prefix: "power-IT-TSSB"
  name: all
  scenarios:
    enable: true
    file: config/instances/scenarios/scenarios-TSSB-power.yaml
  disable_progressbar: true
  shared_resources:
    policy: false
    exclude: []
  use_shadow_directory: false

foresight: overnight

scenario:
  clusters:
  - 5
  - 10
  - 20
  - 50
  - 100

  opts:
  - ''

clustering:
  temporal:
    resolution_elec: 48c24

solving:
  options:
    load_shedding: 
      enable: true
    skip_iterations: true
    transmission_losses: 0
    linearized_unit_commitment: false
    noisy_costs: false
  solver:
    name: [gurobi, smspp]
    options: [gurobi-default, smspp-tssb]
  solver_options:
    "smspp-tssb":
      stochastic_parameters:
        stochastic_type: tssb
        capacity_expansion_ucblock: true
        configfile: "TSSB/tssb_solverconfig_grb.txt"
        parameters:
        - demand
  runtime: 12H
  