th_24c24_demand_3:
  clustering:
    temporal:
      resolution_elec: 24c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_3.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand

th_120c24_demand_3:
  clustering:
    temporal:
      resolution_elec: 120c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_3.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand

th_365c24_demand_3:
  clustering:
    temporal:
      resolution_elec: 1H
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_3.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand

th_24c24_demand_10:
  clustering:
    temporal:
      resolution_elec: 24c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_10.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand

th_120c24_demand_10:
  clustering:
    temporal:
      resolution_elec: 120c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_10.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand

th_365c24_demand_10:
  clustering:
    temporal:
      resolution_elec: 1H
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_10.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand


th_24c24_demand_20:
  clustering:
    temporal:
      resolution_elec: 24c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_20.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand

th_120c24_demand_20:
  clustering:
    temporal:
      resolution_elec: 120c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_20.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand

th_365c24_demand_20:
  clustering:
    temporal:
      resolution_elec: 1H
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_20.yaml
  solving:
    solver_options:
      smspp-tssb:
        stochastic_parameters:
          parameters:
          - demand