th_24c24_demand:
  clustering:
    temporal:
      resolution_elec: 24c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_3.yaml
  solving:
    solver_options:
      smspp-tssb: &th_24c24_demand
        stochastic_parameters:
          parameters:
          - demand
      smspp-tssb-bds: *th_24c24_demand
      smspp-tssb-lds: *th_24c24_demand
      smspp-tssb-ldld: *th_24c24_demand
      smspp-tssb-ldrec: *th_24c24_demand
      smspp-tssb-pph: *th_24c24_demand

th_48c24_demand:
  clustering:
    temporal:
      resolution_elec: 48c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_3.yaml
  solving:
    solver_options:
      smspp-tssb: &th_48c24_demand
        stochastic_parameters:
          parameters:
          - demand
      smspp-tssb-bds: *th_48c24_demand
      smspp-tssb-lds: *th_48c24_demand
      smspp-tssb-ldld: *th_48c24_demand
      smspp-tssb-ldrec: *th_48c24_demand
      smspp-tssb-pph: *th_48c24_demand

th_168c24_demand:
  clustering:
    temporal:
      resolution_elec: 168c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_3.yaml
  solving:
    solver_options:
      smspp-tssb: &th_168c24_demand
        stochastic_parameters:
          parameters:
          - demand
      smspp-tssb-bds: *th_168c24_demand
      smspp-tssb-lds: *th_168c24_demand
      smspp-tssb-ldld: *th_168c24_demand
      smspp-tssb-ldrec: *th_168c24_demand
      smspp-tssb-pph: *th_168c24_demand

th_365c24_demand:
  clustering:
    temporal:
      resolution_elec: 1H
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-demand_3.yaml
  solving:
    solver_options:
      smspp-tssb: &th_365c24_demand
        stochastic_parameters:
          parameters:
          - demand
      smspp-tssb-bds: *th_365c24_demand
      smspp-tssb-lds: *th_365c24_demand
      smspp-tssb-ldld: *th_365c24_demand
      smspp-tssb-ldrec: *th_365c24_demand
      smspp-tssb-pph: *th_365c24_demand

th_24c24_renewable:
  clustering:
    temporal:
      resolution_elec: 24c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-renewable-maxpower_3.yaml
  solving:
    solver_options:
      smspp-tssb: &th_24c24_renewable
        stochastic_parameters:
          parameters:
          - renewable_maxpower
      smspp-tssb-bds: *th_24c24_renewable
      smspp-tssb-lds: *th_24c24_renewable
      smspp-tssb-ldld: *th_24c24_renewable
      smspp-tssb-ldrec: *th_24c24_renewable
      smspp-tssb-pph: *th_24c24_renewable

th_48c24_renewable:
  clustering:
    temporal:
      resolution_elec: 48c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-renewable-maxpower_3.yaml
  solving:
    solver_options:
      smspp-tssb: &th_48c24_renewable
        stochastic_parameters:
          parameters:
          - renewable_maxpower
      smspp-tssb-bds: *th_48c24_renewable
      smspp-tssb-lds: *th_48c24_renewable
      smspp-tssb-ldld: *th_48c24_renewable
      smspp-tssb-ldrec: *th_48c24_renewable
      smspp-tssb-pph: *th_48c24_renewable

th_168c24_renewable:
  clustering:
    temporal:
      resolution_elec: 168c24
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-renewable-maxpower_3.yaml
  solving:
    solver_options:
      smspp-tssb: &th_168c24_renewable
        stochastic_parameters:
          parameters:
          - renewable_maxpower
      smspp-tssb-bds: *th_168c24_renewable
      smspp-tssb-lds: *th_168c24_renewable
      smspp-tssb-ldld: *th_168c24_renewable
      smspp-tssb-ldrec: *th_168c24_renewable
      smspp-tssb-pph: *th_168c24_renewable

th_365c24_renewable:
  clustering:
    temporal:
      resolution_elec: 1H
  stochastic_scenarios:
    file: config/instances/scenarios/tssb/stochastic-renewable-maxpower_3.yaml
  solving:
    solver_options:
      smspp-tssb: &th_365c24_renewable
        stochastic_parameters:
          parameters:
          - renewable_maxpower
      smspp-tssb-bds: *th_365c24_renewable
      smspp-tssb-lds: *th_365c24_renewable
      smspp-tssb-ldld: *th_365c24_renewable
      smspp-tssb-ldrec: *th_365c24_renewable
      smspp-tssb-pph: *th_365c24_renewable
