renewable_scenario: &renewable_scenario
  name: modify_components
  params:
    rules:
    - component: Generator
      attribute: p_max_pu
      target: auto
      carrier: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]
      operation: scale
      value:
        distribution: normal
        mean: 1.0
        std: 0.1
        min: 0.8
        max: 1.2
        seed: 456

scenarios:
  renewable_01: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_02: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_03: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_04: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_05: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_06: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_07: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_08: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_09: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_10: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_11: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_12: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_13: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_14: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_15: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_16: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_17: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_18: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_19: {prob: 0.05, structured_scenario: *renewable_scenario}
  renewable_20: {prob: 0.05, structured_scenario: *renewable_scenario}
