renewable_scenario: &renewable_scenario
  name: modify_components
  params:
    rules:
    - component: Generator
      attribute: p_max_pu
      target: auto
      carrier: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]
      operation: scale
      value:
        distribution: normal
        mean: 1.0
        std: 0.1
        min: 0.8
        max: 1.2
        seed: 456

scenarios:
  renewable_01: {prob: 0.3333333333, structured_scenario: *renewable_scenario}
  renewable_02: {prob: 0.3333333334, structured_scenario: *renewable_scenario}
  renewable_03: {prob: 0.3333333333, structured_scenario: *renewable_scenario}
